djangoProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from djangoProject import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('user/', include('user.urls')),
                  path('product/', include('product.urls')),
                  path('seller/', include('seller.urls')),
                  path('', include('index.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('', views.index, name='index'),
    # path('create-product/', views.create_product, name='create-product'),
    path('create-product/<str:product_type>/', views.ProductCreateView.as_view(), name='create-product'),
    path('edit-product/<str:product_type>/<int:pk>/', views.ProductUpdateView.as_view(), name='edit-product'),
    path('delete-product/<int:pk>/', views.delete_product, name='delete-product'),
    # path('edit-product/<int:product_id>/', views.edit_product, name='edit-product'),
    path('your-products/', views.your_products, name='your-products'),
]

user/urls.py
from . import views
from django.urls import path, include

app_name = 'user'

urlpatterns = [
    path('login/', views.login_to, name='login'),
    path('sign-up/', views.sign_up, name='sign-up'),
    path('logout/', views.logout_from, name='logout'),
]

product/models.py
from django.db import models


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    description = models.TextField()
    image = models.ImageField(upload_to='product/images/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    brand = models.ForeignKey('Brand', on_delete=models.CASCADE)
    seller = models.ForeignKey('seller.Seller', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name


class Book(Product):
    author = models.CharField(max_length=255)
    pages = models.IntegerField()
    publisher = models.CharField(max_length=255)
    published_at = models.DateField()

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

product/forms.py
from django import forms
from .models import Product, Category, Brand, Book


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        exclude = ['created_at', 'updated_at', 'seller']


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        exclude = ['created_at', 'updated_at']


class BrandForm(forms.ModelForm):
    class Meta:
        model = Brand
        fields = '__all__'
        exclude = ['created_at', 'updated_at']


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'
        exclude = ['created_at', 'updated_at', 'seller']

product/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView

from seller.models import Seller
from .models import *
from .forms import *


# Create your views here.
def index(request):
    return render(request, 'product/list-product.html')


class ProductUpdateView(UpdateView):
    template_name = 'product/edit-product.html'
    success_url = reverse_lazy('index:index')

    def get_form_class(self):
        product_type = self.kwargs['product_type']
        if product_type == 'book':
            return BookForm
        else:
            return ProductForm

    def get_model(self):
        product_type = self.kwargs['product_type']
        if product_type == 'book':
            return Book
        else:
            return Product

    def get_queryset(self):
        product_type = self.kwargs['product_type']
        if product_type == 'book':
            return Book.objects.all()
        else:
            return Product.objects.all()

    def get_object(self, queryset=None):
        product = super().get_object(queryset)
        return product

    def form_valid(self, form):
        form.instance.seller = Seller.objects.get(user=self.request.user)
        return super().form_valid(form)


def your_products(request):
    seller = Seller.objects.get(user=request.user)
    products = Product.objects.filter(seller=seller)
    return render(request, 'product/your-products.html', {'products': products})


class ProductCreateView(CreateView):
    template_name = 'product/create-product.html'
    success_url = reverse_lazy('index:index')

    def get_form_class(self):
        product_type = self.kwargs['product_type']
        if product_type == 'book':
            return BookForm
        else:
            return ProductForm

    def get_model(self):
        product_type = self.kwargs['product_type']
        if product_type == 'book':
            return Book
        else:
            return Product

    def form_valid(self, form):
        form.instance.seller = Seller.objects.get(user=self.request.user)
        return super().form_valid(form)


def delete_product(request, pk):
    product = Product.objects.get(id=pk)
    user = request.user
    if product.seller.user != user:
        return redirect('product:your-products')
    product.delete()
    return redirect('product:your-products')

product/templates/product/create-product.html
{% extends '_base.html' %}
{% load widget_tweaks %}
{% block title %}
    Product Form
{% endblock %}


{% block content %}

    <h2 class="text-center mt-3">Selling a product</h2>
    <div class="w-50 mx-auto">
        <form method="post" enctype="multipart/form-data" class="form-group" action="{% url 'product:create-product' %}">
            {% csrf_token %}
            {% for field in form %}
                <div class="mb-3">
                    {{ field.label_tag }}<br>
                    {% render_field field class="form-control" %}
                    {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                    {% if field.errors %}
                        <div class="alert alert-danger">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>


{% endblock %}

product/templates/product/edit-product.html
{% extends '_base.html' %}
{% load widget_tweaks %}
{% block title %}
    Product Form
{% endblock %}


{% block content %}

    <h2 class="text-center mt-3">Editing Product</h2>
    <div class="w-50 mx-auto">
        <form method="post" enctype="multipart/form-data" class="form-group">
            {% csrf_token %}
            {% for field in form %}
                <div class="mb-3">
                    {{ field.label_tag }}<br>
                    {% render_field field class="form-control" %}
                    {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                    {% if field.errors %}
                        <div class="alert alert-danger">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>


{% endblock %}

product/templates/product/list-product.html
{% load static %}


<div class="container">

    <div class="row d-xl-flex d-xxl-flex justify-content-xl-center justify-content-xxl-center align-items-xxl-center">

        <div class="col-6 col-lg-3 col-xl-2 col-xxl-2 text-center">
            <picture><img class="w-100 fit-cover" src="{% static 'img/9781718502703-2057475121.jpg' %}"
                          style="width: 200px;"/>
            </picture>
            <div>
                <p class="text-start"><span style="color: rgb(0, 0, 0);">Python Crash Course, 3rd Edition: A Hands-On, Project-Based Introduction to Programming</span>
                </p>
            </div>
            <div class="text-start"><a href="#"><span style="color: rgb(86, 89, 89);">by </span><span
                    style="color: rgb(10, 17, 200);">Eric Matthes</span></a></div>
            <div class="d-flex d-xl-flex align-items-center align-items-xl-center"><span
                    style="margin-right: 10px;"><i class="fas fa-star" style="color: var(--bs-yellow);"></i><i
                    class="fas fa-star" style="color: var(--bs-yellow);"></i><i class="fas fa-star"
                                                                                style="color: var(--bs-yellow);"></i><i
                    class="fas fa-star" style="color: var(--bs-yellow);"></i><i class="fas fa-star"
                                                                                style="color: var(--bs-tertiary-color);"></i></span><i
                    class="fas fa-angle-down" style="color: var(--bs-tertiary-color);"></i><span
                    style="color: var(--bs-link-hover-color);">790</span></div>
            <p class="text-start"><span style="margin-right: 10px;font-size: 32px;">$31<sup>99</sup></span><span
                    style="text-decoration: line-through;">$41.99</span></p>
        </div>


    </div>

</div>

product/templates/product/your-products.html
{% extends '_base.html' %}

{% block title %}
    List Product of {{ user.username }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row d-xl-flex d-xxl-flex justify-content-xl-center justify-content-xxl-center align-items-xxl-center">
            {% for product in products %}

                <div class="col-6 col-lg-3 col-xl-2 col-xxl-2 text-center">
                    {% if product.book %}

                        <a href="{% url 'product:edit-product' product_type='book' pk=product.id %}">

                            <picture><img class="w-100 fit-cover" src="{{ product.image.url }}"
                                          style="width: 200px;" alt="{{ product.name }}"/>
                            </picture>
                        </a>
                    {% else %}
                        <a href="{% url 'product:edit-product' product_type='other' pk=product.id %}">
                            <picture><img class="w-100 fit-cover" src="{{ product.image.url }}"
                                          style="width: 200px;" alt="{{ product.name }}"/>
                            </picture>
                        </a>
                    {% endif %}

                    <div>
                        <p class="text-start"><span style="color: rgb(0, 0, 0);">
                            {{ product.name }}
                        </span>
                        </p>
                    </div>
                    <div class="text-start">

                        <span>by </span>
                        <span>
                                {% if product.book %}
                                    <a style="color: #4900c8">{{ product.book.author }}</a>
                                {% endif %}
                            </span>

                    </div>
                    <div class="d-flex d-xl-flex align-items-center align-items-xl-center"><span
                            style="margin-right: 10px;"><i class="fas fa-star" style="color: var(--bs-yellow);"></i><i
                            class="fas fa-star" style="color: var(--bs-yellow);"></i><i class="fas fa-star"
                                                                                        style="color: var(--bs-yellow);"></i><i
                            class="fas fa-star" style="color: var(--bs-yellow);"></i><i class="fas fa-star"
                                                                                        style="color: var(--bs-tertiary-color);"></i></span><i
                            class="fas fa-angle-down" style="color: var(--bs-tertiary-color);"></i><span
                            style="color: var(--bs-link-hover-color);">790</span></div>
                    {% with product.price|floatformat:2 as formatted_price %}
                        <p class="text-start">
                            <span style="margin-right: 10px;font-size: 32px;">${{ formatted_price|slice:":-3" }}<sup>{{ formatted_price|slice:"-2:" }}</sup></span><span
                                style="text-decoration: line-through;">$41.99</span>
                        </p>
                    {% endwith %}

                </div>
                <a href="{% url 'product:delete-product' pk=product.id %}" class="text-danger">Detete</a>

            {% endfor %}

        </div>
    </div>
{% endblock %}