djangoProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from djangoProject import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('user/', include('user.urls')),
                  path('product/', include('product.urls')),
                  path('seller/', include('seller.urls')),
                  path('', include('index.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('', views.index, name='index'),
    # path('create-product/', views.create_product, name='create-product'),
    path('create-product/<str:product_type>/', views.ProductCreateView.as_view(), name='create-product'),
    path('edit-product/<str:product_type>/<int:pk>/', views.ProductUpdateView.as_view(), name='edit-product'),
    path('delete-product/<int:pk>/', views.delete_product, name='delete-product'),
    # path('edit-product/<int:product_id>/', views.edit_product, name='edit-product'),
    path('your-products/', views.your_products, name='your-products'),
]

seller/urls.py
from django.urls import path
from . import views

app_name = 'seller'

urlpatterns = [
    path('register-seller/', views.register, name='register-seller'),
]

user/urls.py
from . import views
from django.urls import path, include

app_name = 'user'

urlpatterns = [
    path('login/', views.login_to, name='login'),
    path('sign-up/', views.sign_up, name='sign-up'),
    path('logout/', views.logout_from, name='logout'),
]

templates/_base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <title>
        {% block title %}

        {% endblock %}
    </title>
    <!-- Required meta tags -->
    <meta charset="utf-8"/>
    <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    {% block link %}
	
    {% endblock %}

    <!-- Bootstrap CSS v5.2.1 -->
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>

<body>
<header>
    <!-- place navbar here -->
    {% include '_header.html' %}
</header>
{% block content %}

{% endblock %}
<footer>
    <!-- place footer here -->
</footer>
<!-- Bootstrap JavaScript Libraries -->
<script
        src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"
></script>

<script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"
></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
</body>
</html>

templates/_header.html
{% load static %}

<header>
    <div class="container-fluid" style="background: #DBE2EF;">
        <nav class="navbar navbar-expand-md sticky-top navbar-light" style="background: #DBE2EF;">
            <div class="container-fluid"><a class="navbar-brand" href="/" style="margin-right: -354px;"><img
                    class="w-25 fit-cover" src="{% static 'img/bird.svg' %}"></a>
                <button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-2"><span
                        class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navcol-2" style="color: var(--bs-body-bg);">
                    <div class="dropdown"><a class="dropdown-toggle nav-link" aria-expanded="false"
                                             data-bs-toggle="dropdown" href="#" style="color: #112D4E;">Book </a>
                        <div class="dropdown-menu" style="color: #112D4E;">
                            <a class="dropdown-item" href="{% url 'product:create-product' product_type='book'  %}"
                               style="color: #112D4E;">Sell Book</a><a
                                class="dropdown-item" href="#" style="color: #112D4E;">Second Item</a><a
                                class="dropdown-item" href="#" style="color: #112D4E;">Third Item</a></div>
                    </div>
                    <ul class="navbar-nav" style="color: #112D4E;">
                        <li class="nav-item" style="color: #112D4E;"><a class="nav-link active"
                                                                        href="{% url 'product:create-product' product_type='product' %}"
                                                                        style="color: #112D4E;">Create Product</a></li>
                        <li class="nav-item" style="color: #112D4E;"><a class="nav-link"
                                                                        href="{% url 'seller:register-seller' %}"
                                                                        style="color: #112D4E;">Become a Seller</a></li>
                        <li class="nav-item" style="color: #112D4E;"><a class="nav-link"
                                                                        href="{% url 'product:your-products' %}"
                                                                        style="color: #112D4E;">Your Products</a></li>
                    </ul>
                    {% if user.is_authenticated %}
                        <div class="col d-flex d-sm-flex d-md-flex d-xl-flex justify-content-center justify-content-sm-center align-items-sm-center justify-content-md-center align-items-md-center justify-content-xl-end align-items-xl-center"
                             style="margin: 10px;margin-right: 14px;"><i class="far fa-user d-flex align-items-center"
                                                                         style="font-size: 34px;margin-right: 3px;padding: 5px;padding-top: 5px;color: var(--bs-tertiary-color);background: var(--bs-secondary-bg);border-radius: 50%;"></i>
                            <p style="margin-top: 11px;font-weight: bold;" class="text-black">{{ user.username }}</p>

                            <a class="btn btn-primary" type="button" style="margin-left: 20px;"
                               href="{% url 'user:logout' %}">Sign Out</a>
                        </div>
                    {% else %}
                        <ul class="navbar-nav ms-auto">
                            <li class="nav-item"><a class="nav-link active text-decoration-underline"
                                                    href="{% url 'user:login' %}">
                                Login
                            </a></li>

                            <li class="nav-item"><a
                                    class="nav-link text-decoration-underline"
                                    href="{% url 'user:sign-up' %}">
                                Sign Up
                            </a></li>

                        </ul>
                    {% endif %}

                </div>
            </div>
        </nav>


    </div>
</header>
<script src="{% static "js/bootstrap.min.js" %}"></script>